### ISSUE TITLE
Auth Beta - no way to 'logout' with sessions

### ISSUE THREAD

**Issue by 0xTim** [vapor/auth#18]
With the current beta, it is just missing an `unauthenticate` function to remove the authenticated user from the session to log the user out. Adding here as a reminder so I don't forget!

**Comment by tanner0101** [comment]
"Un-authing" should only apply to sessions-based auth, right? If sessions aren't be used, then the auth only lasts for the lifetime of the request. If so, there's `req.session().destroy()`.

Although perhaps it's useful to unauth a user even if it only lives for the duration of one request. Potentially you'd want to avoid the user being authed for some logic downstream.

**Comment by 0xTim** [comment]
Yeah I'm mainly thinking about sessions here, the compliment of `req.authenticateSession(user)` - so something like `req.unauthenticateSession(user)` that will destroy the session for the provided user under the hood
