### ISSUE TITLE
Auth 2 - Cookies not working in Safari Tech Preview

### ISSUE THREAD

**Issue by 0xTim** [vapor/auth#28]
STP Release 50 - session cookies are not working correctly, after authentication if I try and access a protected route it redirects me back using the RedirectMiddleware. Works fine in Firefox, Chrome and normal Safari. Adding here to remind me to investigate further, either Vapor (unlikely since it works fine in others) or a STP bug that needs filing in a radar

**Comment by tanner0101** [comment]
This is probably resolved in the NIO branch already, but I need to double check.

**Comment by 0xTim** [comment]
Either fixed in NIO or the latest Safari Tech Preview!

**Comment by robipresotto** [comment]
Currently having the same issue at AWS ECS fargate instance. Works fine locally. 

[https://ibb.co/ntJbKz](url)
