### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by zdnk** [vapor/auth#49]
Is stable release coming any time soon?
It is limiting us to Vapor2 for now.

**Comment by 0xTim** [comment]
There are a few outstanding issues but it's mostly stable. If you join the Discord server you can see the status of releases (basically it's Leaf in progress now then Auth)

**Comment by tanner0101** [comment]
I'm working on the documentation now. Should be coming shortly. Thanks for your patience!

**Comment by tanner0101** [comment]
Finally here: https://github.com/vapor/auth/releases/tag/2.0.0 :)
