### ISSUE TITLE
Route using SQLite model and SessionMiddleware timeouts when ran on ubuntu.

### ISSUE THREAD

**Issue by ArnaudMiguet** [vapor/auth#50]
**Description**
When deploying project on ubuntu on a VPS, I ran into timeouts on a route that uses a Fluent SQLite Model. 
The project is running fine when ran on Mac. 

**Environment**
- Ubuntu 16.04
- Swift up to date
- Vapor up to date
- Dependencies up to date

**Conditions** (based on my observations)
- Use SessionMiddleware
- Use SQLiteCache for KeyedCache
- Use SQLite Fluent Model
- Use sessions from within a Future returned by fluent

Here is a zip containing a sample project (reduced from my project), in which the login post route is affected by the issue : 
[Workshop copie.zip](https://github.com/vapor/auth/files/2249872/Workshop.copie.zip)

**Comment by ArnaudMiguet** [comment]
Based on a discussion on Discord, it seems to be related to my VPS having only 1 core available to me. Does it help to fix the issue ?

**Comment by tanner0101** [comment]
@NohVender try increasing your connection pool size. See [`DatabaseConnectionPoolConfig`](https://api.vapor.codes/database-kit/latest/DatabaseKit/Structs/DatabaseConnectionPoolConfig.html).

**Comment by ArnaudMiguet** [comment]
Oh ok, I'll look into it and close if it helps.

**Comment by NohVender** [comment]
Does not help ... I used this in my conf file :
` let db_config = DatabaseConnectionPoolConfig(maxConnections: 20)
    services.register(db_config)`
But still getting timeouts

**Comment by NohVender** [comment]
@tanner0101 New small project using DatabaseConnectionPoolConfig but still buggy on single core ubuntu environment : 

[Workshop.zip](https://github.com/vapor/auth/files/2277065/Workshop.zip)

**Comment by NohVender** [comment]
I can confirm that manually changing the default value of DatabaseConnectionPoolConfig does solve the problem. Just need a way to set it for SQLiteCache now. Does the default value of System.coreCount make sense though ?

**Comment by ArnaudMiguet** [comment]
@tanner0101 Alright I got it working !  Still wonder if the default value needs to be System.coreCount which was set to 1 on my VPS
