### ISSUE TITLE
Problem with Auth 2.0.2

### ISSUE THREAD

**Issue by clbaeza** [vapor/auth#61]
![captura de pantalla 2019-02-18 a la s 11 45 32 a m](https://user-images.githubusercontent.com/4458573/52958477-e737e880-3372-11e9-9814-aa07a747225c.png)

**Comment by vzsg** [comment]
In an unfortunate turn of events, vapor/auth 2.0.2 depends on changes that went live with Vapor 3.2.0. Therefore, you need to update your project's dependencies.

Close Xcode, then run the following commands:

```
swift package update
swift package generate-xcodeproj
```

Then open the project again.

**Comment by clbaeza** [comment]
Thanks for the reply.
Now it works.
