### ISSUE TITLE
/Sources/Authentication/Persist/SessionAuthenticatable.swift:44:19: error: value of type 'Request' has no member 'hasSession'; did you mean 'session'?

### ISSUE THREAD

**Issue by DaniilWolfe** [vapor/auth#63]
With Auth 2.0.2 included a clean project will not compile due to this error. Once I rolled back to 2.0.1 everything worked fine.

**Comment by 0xTim** [comment]
@WuDanlong this was due to a dependency error, which has been fixed in [2.0.3](https://github.com/vapor/auth/releases/tag/2.0.3). You can also run `swift package update` to pull in the new Vapor version that contains `hasSession`

**Comment by DaniilWolfe** [comment]
Thanks Tim
